### ISSUE TITLE
Direct registration of DDTracer without agent fails

### ISSUE THREAD

**Issue by jrogers** [DataDog/dd-trace-java#2912]
We have some unit test code that tests our tracing extensions without having the agent configured. To do so we follow the instructions - https://docs.datadoghq.com/tracing/setup_overview/open_standards/java/ - but they no longer work on 0.83.1 (not sure when this stopped working tbh, we are updating this from 0.67), and fail with the following error:
```
java.lang.NoClassDefFoundError: datadog/communication/monitor/Monitoring

	at datadog.opentracing.DDTracer.<init>(DDTracer.java:346)
	at datadog.opentracing.DDTracer.<init>(DDTracer.java:40)
	at datadog.opentracing.DDTracer$DDTracerBuilder.build(DDTracer.java:167)
	...
```

Ex snippet in our test setup:
```
import datadog.opentracing.DDTracer
import io.opentracing.util.GlobalTracer

        val ddTracer =
            DDTracer.builder()
                .build()

        GlobalTracer.registerIfAbsent(ddTracer)
```

and with:
```
            <dependency>
                <groupId>com.datadoghq</groupId>
                <artifactId>dd-trace-api</artifactId>
                <version>0.83.1</version>
            </dependency>
            <dependency>
                <groupId>com.datadoghq</groupId>
                <artifactId>dd-trace-ot</artifactId>
                <version>0.83.1</version>
            </dependency>
```

Looks like a dependency packaging issue. The code from the communication module is excluded from the api/ot libs.

**Comment by mcculls** [comment]
Hi Jeff, yes the new communication module was accidentally omitted from `dd-trace-ot` - we'll get this fixed asap

**Comment by mcculls** [comment]
Hi Jeff, this will be fixed in the next release - I'll update this issue when it's available.

Until then one workaround is to use a previous release (anything before 0.83.0 should work)

**Comment by mcculls** [comment]
The 0.83.2 release should now work as expected
