### PR TITLE
Bundle new communication module with dd-trace-ot

### LINKED ISSUE #2912: Direct registration of DDTracer without agent fails
We have some unit test code that tests our tracing extensions without having the agent configured. To do so we follow the instructions - https://docs.datadoghq.com/tracing/setup_overview/open_standards/java/ - but they no longer work on 0.83.1 (not sure when this stopped working tbh, we are updating this from 0.67), and fail with the following error:
```
java.lang.NoClassDefFoundError: datadog/communication/monitor/Monitoring

	at datadog.opentracing.DDTracer.<init>(DDTracer.java:346)
	at datadog.opentracing.DDTracer.<init>(DDTracer.java:40)
	at datadog.opentracing.DDTracer$DDTracerBuilder.build(DDTracer.java:167)
	...
```

Ex snippet in our test setup:
```
import datadog.opentracing.DDTracer
import io.opentracing.util.GlobalTracer

        val ddTracer =
            DDTracer.builder()
                .build()

        GlobalTracer.registerIfAbsent(ddTracer)
```

and with:
```
            <dependency>
                <groupId>com.datadoghq</groupId>
                <artifactId>dd-trace-api</artifactId>
                <version>0.83.1</version>
            </dependency>
            <dependency>
                <groupId>com.datadoghq</groupId>
                <artifactId>dd-trace-ot</artifactId>
                <version>0.83.1</version>
            </dependency>
```

Looks like a dependency packaging issue. The code from the communication module is excluded from the api/ot libs.

### PR DESCRIPTION
**Pull request by mcculls**
Fixes #2912

### CODE REVIEW

**Review by tylerbenson — APPROVED** [review]
We need to test this somehow.

**Review by richardstartin — APPROVED** [review]
