### ISSUE TITLE
Regression in 0.26.0

### ISSUE THREAD

**Issue by marcust** [DataDog/dd-trace-java#779]
I just had a system die after upgrading to 0.26.0. I'm not super sure what happened, but apparently there are some class loading issues. 

I see some  `java.lang.NoClassDefFoundError` for
`datadog/trace/bootstrap/instrumentation/context/FieldBackedProvider$ContextAccessor$java$net$HttpURLConnection$datadog$trace$instrumentation$http_url_connection$HttpUrlConnectionInstrumentation$HttpUrlState` coming from `sun.net.www.protocol.https.Handler.openConnection`.

**Comment by aantono** [comment]
Duplicate of #780

**Comment by tylerbenson** [comment]
Thanks for the report. Well take a look at this ASAP.

**Comment by tylerbenson** [comment]
What JDK version are you using?

**Comment by marcust** [comment]
@tylerbenson 
```openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Debian-3bpo91)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Debian-3bpo91, mixed mode)```

**Comment by mar-kolya** [comment]
@marcust Could you please try this snapshot build and let is know if it fixes the problem: https://21032-89221572-gh.circle-artifacts.com/0/home/circleci/dd-trace-java/libs/dd-java-agent-0.27.0-SNAPSHOT.jar ?
Thanks!

**Comment by marcust** [comment]
@mar-kolya Looks good to me, at least with one case that I could reproduce it with I can't anymore.

**Comment by tylerbenson** [comment]
The fix for this is released, but shortly after we discovered a bigger issue with `0.26.0-1` around traces being rejected by the agent and should have a fix for that released ASAP.  You'll want to wait for that to upgrade.
